version: '3.3'
services:
    rabbitmq:
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '8080:15672'
#        image: 'rabbitmq:3.8-management'
        build: .
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbit